"""Add audit log migration

Revision ID: 4e976bcf7a39
Revises: 
Create Date: 2019-03-12 08:10:04.316011
"""

from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision = '4e976bcf7a39'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', backend.database.types.GUID(), nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('state_before', sa.Text(), nullable=True),
    sa.Column('state_after', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
